#!/usr/bin/env python3
"""
Monitoring Report Analyzer for Cipher Quiz

Analyzes the detailed monitoring reports generated by the orchestrator
to provide insights into agent behavior and potential cheating attempts.
"""

import json
import sys
from pathlib import Path
import argparse

def analyze_monitoring_report(report_path: Path) -> None:
    """Analyze a single monitoring report file."""
    try:
        report = json.loads(report_path.read_text())
    except (json.JSONDecodeError, FileNotFoundError) as e:
        print(f"❌ Could not read {report_path}: {e}")
        return
    
    print(f"\n📊 Analysis of {report_path.name}")
    print("=" * 50)
    
    # File access analysis
    file_access = report.get("file_access", {})
    if "total_file_operations" in file_access:
        print(f"📁 Total file operations: {file_access['total_file_operations']}")
        print(f"📂 Unique files accessed: {file_access.get('unique_files_accessed', 0)}")
        
        # Show accessed files
        accessed_files = file_access.get("all_accessed_files", [])
        if accessed_files:
            print(f"\n📋 Files accessed:")
            for i, filepath in enumerate(accessed_files[:10]):  # Show first 10
                print(f"  {i+1:2}. {filepath}")
            if len(accessed_files) > 10:
                print(f"  ... and {len(accessed_files) - 10} more")
        
        # Security analysis
        suspicious = file_access.get("suspicious_activities", [])
        if suspicious:
            print(f"\n🚨 Suspicious Activities Found:")
            for activity in suspicious:
                severity_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(activity.get("severity", "LOW"), "⚪")
                print(f"  {severity_emoji} {activity['type']}: {activity['description']}")
        else:
            print(f"\n✅ No suspicious file access detected")
        
        # Risk assessment
        severity_counts = file_access.get("severity_counts", {})
        total_issues = sum(severity_counts.values())
        if total_issues == 0:
            print(f"🟢 Risk Level: LOW (Clean execution)")
        elif severity_counts.get("HIGH", 0) > 0:
            print(f"🔴 Risk Level: HIGH ({severity_counts['HIGH']} high-severity issues)")
        elif severity_counts.get("MEDIUM", 0) > 0:
            print(f"🟡 Risk Level: MEDIUM ({severity_counts['MEDIUM']} medium-severity issues)")
        else:
            print(f"🟢 Risk Level: LOW ({total_issues} minor issues)")
    
    # Solution quality analysis
    solution_quality = report.get("solution_quality", {})
    if solution_quality:
        print(f"\n🎯 Solution Quality Analysis:")
        if solution_quality.get("suspicious", False):
            print(f"  🚨 Potentially suspicious: {solution_quality.get('reason', 'Unknown')}")
        else:
            print(f"  ✅ Normal solution pattern detected")
    
    # Performance metrics
    stdout_length = report.get("stdout_length", 0)
    stderr_length = report.get("stderr_length", 0)
    print(f"\n⚡ Performance Metrics:")
    print(f"  📤 Output length: {stdout_length:,} chars")
    if stderr_length > 0:
        print(f"  ⚠️  Error output: {stderr_length:,} chars")
    else:
        print(f"  ✅ No errors reported")


def analyze_all_reports(workspace_dir: Path, summary_only: bool = False) -> None:
    """Analyze all monitoring reports in a workspace directory."""
    # Look for reports in both workspaces and monitoring_reports directories
    workspace_reports = list(workspace_dir.rglob("monitoring_report.json"))
    
    # Also check for preserved reports in monitoring_reports/
    monitoring_reports_dir = workspace_dir.parent / "monitoring_reports" if workspace_dir.name != "monitoring_reports" else workspace_dir
    preserved_reports = []
    if monitoring_reports_dir.exists():
        preserved_reports = list(monitoring_reports_dir.glob("*_monitoring.json"))
    
    all_reports = workspace_reports + preserved_reports
    
    if not all_reports:
        print(f"❌ No monitoring reports found in {workspace_dir}")
        if monitoring_reports_dir.exists():
            print(f"   Also checked: {monitoring_reports_dir}")
        print(f"   Hint: Run orchestrator with --enable-monitoring to generate reports")
        return
    
    print(f"🔍 Found {len(all_reports)} monitoring reports")
    if workspace_reports:
        print(f"   📁 {len(workspace_reports)} in workspaces")
    if preserved_reports:
        print(f"   💾 {len(preserved_reports)} preserved reports")
    
    # Summary statistics
    total_operations = 0
    total_suspicious = 0
    high_risk_rounds = []
    round_stats = {}
    
    for report_path in sorted(all_reports):
        try:
            report = json.loads(report_path.read_text())
            file_access = report.get("file_access", {})
            
            ops = file_access.get("total_file_operations", 0)
            total_operations += ops
            suspicious_count = len(file_access.get("suspicious_activities", []))
            total_suspicious += suspicious_count
            
            # Extract round number from filename
            if "_monitoring.json" in report_path.name:
                round_num = report_path.name.split("_")[1]
            else:
                round_num = report_path.parent.name.replace("round_", "") if "round_" in str(report_path.parent) else "unknown"
            
            round_stats[round_num] = {
                "operations": ops,
                "suspicious": suspicious_count,
                "high_risk": file_access.get("severity_counts", {}).get("HIGH", 0) > 0
            }
            
            if file_access.get("severity_counts", {}).get("HIGH", 0) > 0:
                high_risk_rounds.append(round_num)
                
        except Exception as e:
            print(f"⚠️  Could not analyze {report_path}: {e}")
    
    print(f"\n📈 Overall Summary:")
    print(f"  🔧 Total file operations: {total_operations:,}")
    print(f"  🚨 Total suspicious activities: {total_suspicious}")
    if high_risk_rounds:
        print(f"  🔴 High-risk rounds: {', '.join(high_risk_rounds)}")
    else:
        print(f"  ✅ No high-risk rounds detected")
    
    # Round-by-round summary
    if round_stats:
        print(f"\n📊 Round-by-Round Summary:")
        for round_num in sorted(round_stats.keys(), key=lambda x: int(x) if x.isdigit() else 999):
            stats = round_stats[round_num]
            risk_emoji = "🔴" if stats["high_risk"] else "🟡" if stats["suspicious"] > 0 else "✅"
            print(f"  {risk_emoji} Round {round_num}: {stats['operations']} ops, {stats['suspicious']} suspicious")
    
    # If summary_only is False, show detailed analysis
    if not summary_only:
        print(f"\n" + "="*60)
        print(f"DETAILED ANALYSIS")
        print(f"="*60)
        
        # Analyze individual reports
        for report_path in sorted(all_reports):
            analyze_monitoring_report(report_path)


def main():
    parser = argparse.ArgumentParser(description="Analyze cipher quiz monitoring reports")
    parser.add_argument("path", help="Path to monitoring report file or workspace directory")
    parser.add_argument("--summary", action="store_true", help="Show only summary, not detailed reports")
    args = parser.parse_args()
    
    path = Path(args.path)
    if not path.exists():
        print(f"❌ Path not found: {path}")
        sys.exit(1)
    
    if path.is_file() and path.name == "monitoring_report.json":
        # Analyze single report
        analyze_monitoring_report(path)
    elif path.is_dir():
        # Analyze all reports in directory
        analyze_all_reports(path, args.summary)
    else:
        print(f"❌ Expected monitoring_report.json file or directory, got: {path}")
        sys.exit(1)


if __name__ == "__main__":
    main()
